#!/usr/bin/env bash

set -e # Exit if any command fails

ws_dir=""
start_dir=$(pwd)

# Move to workspace directory
cd "$ws_dir"

# Build the enviroment
if [ $# -eq 0 ]; then
        colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
else
        colcon build --packages-select "$@" --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
fi

# Make sure enviroment is up to date
source install/setup.bash

# Move back to starting directory
cd "$start_dir"
